spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liujg001002/SpringcloudConfig.git #码云版https://github.com/liujg001002/SpringcloudConfig.git
          search-paths: respo
      label: master #默认master 可加可不加
server:
  port: 8550

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/